### ISSUE TITLE
Option to re-fill created previously account

### ISSUE THREAD

**Issue by vbaranov** [PhilippLgh/create-eth-test-account#1]
It would be awesome to have an option to re-fill created previously account by indicating address or the path to keystore file. Or I missed it and it is already available?

**Comment by q9f** [comment]
You can select "Top up existing account" - isn't that what you want?

**Comment by PhilippLgh** [comment]
Think there is a "bug" in the way accounts are scanned. The top up only works on accounts it finds in the keystore. However, generated keys are not written to the keystore but the current working directory. And keys in the current working directory are not scanned.
There are multiple solution paths:
- write keys to the keystore (could be a prompt)
- try to find keys in current working directory
- allow to specify different keystore paths
Option 1 (with prompt) + option 2 sounds like a quick UX improvement.

**Comment by vbaranov** [comment]
>You can select "Top up existing account" - isn't that what you want?

Yes, this is what I want, but in my case, the tool doesn't ask me to top up an existing account. It every time generates a new account:
```
viktor$ npm create eth-test-account
npx: installed 44 in 3.122s
Created new account: 0xdeA1F6cF85194745bEEF146F2897e84D5a2609F9
Generating CAPTCHA for quick check if you are human ;-)
```

```
viktor$ node -v
v10.19.0
viktor$ npm -v
6.14.5
```

macOS Catalina 10.15.4


>Option 1 (with prompt) + option 2 sounds like a quick UX improvement.

Sounds great

**Comment by PhilippLgh** [comment]
It looks for the keystore in this path: https://github.com/ethereum/go-ethereum/wiki/Backup-&-restore#data-directory
If the "top up" option is missing it means the keystore was not found or is empty.
